"""Initial migration.

Revision ID: 42e21e318b97
Revises: 085de91f6d1a
Create Date: 2021-03-03 00:15:50.838408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e21e318b97'
down_revision = '085de91f6d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'phone')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=150), nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
